[project]
name = "sheduler"
version = "0.1.0"
description = ""
authors = [
    {name = "Vadim Yarovoy",email = "v.yarovoy@yadro.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit (>=1.57.0,<2.0.0)"
]

[tool.poetry]
packages = [{include = "sheduler", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
